name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.8

    - name: Assemble Debug APK
      run: gradle assembleDebug
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
